### ISSUE TITLE
Every-time we use save tabs as a session, new window opens..

### ISSUE THREAD

**Issue by T21yx64** [tim-we/tabs-aside#104]
Every-time we use save tabs as a session, new window opens..

there should be some option to enable or disable it, or should be disabled..
as its annoying otherwise..
please let me know if I'm doing anything wrong,...

nevertheless, Awesome addon, thanks alot!!
Keep-up the amazing work!

**Comment by tim-we** [comment]
Sounds like a bug but I cannot reproduce it (with default settings). Can you share what settings you use and perhaps a list of steps to reproduce this behaviour?

**Comment by T21yx64** [comment]
I disabled all addons and issue still persisted but
later figured its probably being caused by another conflicting addon known as [Sync Tab Groups](https://github.com/Morikko/sync-tab-groups).. which was disabled but I then removed it completely and issue was gone.. weird,
Reinstalled to check, found out when you are already in a group, it happens else in new group it doesn't..so disabled it and voila..
My bad..
Thanks for making such a cooL addon!!
