### ISSUE TITLE
Tabs Aside 's Sidebar auto-opens after "Tabs aside"

### ISSUE THREAD

**Issue by irvnriir** [tim-we/tabs-aside#109]
I have the "Session root folder" on Bookmarks Toolbar, the Sidebar closed and do open it to use for `History \ View \ By Last Visited` . I work with huge amount of pages when such Add-On is needed, so the auto-opening literally prevents me from using this one .

**Comment by tim-we** [comment]
I think that workflow you describe should be supported, what do you think would be the best way to implement this? Just add an option to enable/disable sidebar auto-open?

**Comment by irvnriir** [comment]
@tim-we y

**Comment by tim-we** [comment]
Tabs Aside 3.6.0, which includes this feature, is now live on AMO.
