### ISSUE TITLE
Ctrl-click for other Restore tabs behavior doesn't work for macOS

### ISSUE THREAD

**Issue by dvrooman** [tim-we/tabs-aside#11]
On the Mac, ctrl clicking is the same as right clicking, so there is no way to use the "other" restore tab functionality. Changing the behavior to Opt clicking would be fairly standard for Mac apps. Maybe a different default on each platform? Or at least an option for the user to to change the modifier key would help.

**Comment by tim-we** [comment]
Thanks for submitting this, I did not know that. 

Tabs Aside 2 will be released shortly and changes a lot, including the restore functionality:
[Tabs Aside 2: Whats new?](https://github.com/tim-we/tabs-aside/wiki/Tabs-Aside-v2.0:-What's-new%3F)

In case you want to keep using the current version let me know, in that case I will pack a custom version.

**Comment by dvrooman** [comment]
Tabs Aside 2 looks marvelous. I am working around the current issue by setting the preference to just restore and manually deleting sessions right now. Works fine in the short term, no need for a custom version (although, thank you so much for the offer!)

Will current Tab Aside users be notified when version 2 is available?
