### ISSUE TITLE
Another Tabs Aside Extension

### ISSUE THREAD

**Issue by sahil48** [tim-we/tabs-aside#115]
When searching for this repo, I found another Tabs Aside Extension by XFox111. Don't know if any collaboration is worthwhile, but thought I would mention it.

**Comment by tim-we** [comment]
Thanks, I was not aware. Stuff like this is probably better suited for the [discussions section](https://github.com/tim-we/tabs-aside/discussions) ;)

**Comment by sahil48** [comment]
Wow, I never realized Github had that. 😄

**Comment by tim-we** [comment]
Yeah it is new feature
