### ISSUE TITLE
Question: How does saving a session affect bookmarks in another folder

### ISSUE THREAD

**Issue by sahil48** [tim-we/tabs-aside#18]
If I have a bookmark in another folder, and then open the website and set it aside with tabs aside, is the bookmark in the other folder still preserved (i.e. there are two copies of the website in firefox bookmarks, one in session, and the other in the folder it was opened from)? This is a very important feature to me if not already implemented.

**Comment by tim-we** [comment]
Tabs aside will create new bookmarks only within its own folder and will not modify or delete any other bookmarks. To answer your question, yes there will be two copies.

**Comment by sahil48** [comment]
Great! Thanks.
