### ISSUE TITLE
Active sessions don't track new tabs that I opened by myself

### ISSUE THREAD

**Issue by feofan-msk** [tim-we/tabs-aside#20]

**Comment by tim-we** [comment]
Yes that is the intended behavior (currently) as you could have multiple sessions per window.
I guess this is a bit confusing so for improvements on that I created [this issue](#21 ).
As for now you can use the tab context menu (right click on a tab -> Tabs Aside).

**Comment by feofan-msk** [comment]
Yes, it seems logic. But this way you can't add new tabs to particular session, as people usually do

**Comment by tim-we** [comment]
Also tabs opened from within a session (e.g. opening a link in a new tab) automatically adds them to the session.
