### ISSUE TITLE
Improve lazy tab loading

### ISSUE THREAD

**Issue by sahil48** [tim-we/tabs-aside#24]
I appreciate that tabs aside respects my browsers memory usage. One of the disadvantages is that when I go through tabs from left to right, I have to wait for each page to load to see if it is a page I am interested in.

It would be great if tabs aside would also preload the two tabs to the right of the current active tab for this workflow.

**Comment by tim-we** [comment]
I like that idea, I will add this. I am also planning to add an option to disable the "unloaded tabs" feature completely.
