### ISSUE TITLE
Option to disable sessions

### ISSUE THREAD

**Issue by ajostergaard** [tim-we/tabs-aside#26]
Actually very much liked the older session-less way Tabs Aside worked. Can we have a session-less mode please.

**Comment by tim-we** [comment]
Yes I am planning to add that option at some point, but it's not a priority right now.
Until then you could of course use the legacy version: https://github.com/tim-we/tabs-aside/releases/tag/v1.17.2

**Comment by tim-we** [comment]
Sorry I forgot to upload the xpi file, thanks for the reminder :) It's there now
