### ISSUE TITLE
Search for existing session

### ISSUE THREAD

**Issue by feofan-msk** [tim-we/tabs-aside#30]
Hi,

Sometimes it's hard to find a particular session, especially when there are more than 10 ones. What do you think about search field at the top?

**Comment by tim-we** [comment]
Sounds like a great idea. I will implement this as soon as I find the time for that :)
I think the easiest way implement this would be to use the [`bookmarks.search()` API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/bookmarks/search) and use those results to determine the sessions.

**Comment by tim-we** [comment]
I just implemented the search feature, this will ship with the release of v3 (which will still take some time unfortunately).

**Comment by tim-we** [comment]
This is implemented in the current build of v3.
![Sidebar Search Preview](https://user-images.githubusercontent.com/10491533/44817446-c376bf80-abe5-11e8-9462-e5d1eaaf3873.PNG)

v3 is still in development, if you want to see it in action check out https://github.com/tim-we/tabs-aside/releases/tag/v3-alpha.1
