### ISSUE TITLE
sidebar layout

### ISSUE THREAD

**Issue by tim-we** [tim-we/tabs-aside#4]
the sidebar is not as "visually appealing compared to set aside in edge"

any suggestions?

**Comment by tim-we** [comment]
"Also, alternate views, like a single list organized by name would be nice too."

**Comment by JordyScript** [comment]
]A good initial goal could be to make it look and feel identical to the edge sidebar.

This could then be made user customizable as well, either by providing different preset tweaks (e.g. different settings for compactness of elements) or even full-fledged themes (dark theme, light theme, with(out) page thumbnails, etc.). These would then be accessible via drop down menus in the Add-on options. 

Optionally one could provide a textbox in the Add-on options where custom CSS can be submitted by the user.

**Comment by tim-we** [comment]
Different themes should relatively easy to implement and would be a nice addition.

There is an [API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/captureVisibleTab) to capture the visible area of the currently active tab so thumbnails would be possible. I am not sure though what would be the best way to store those.

Perhaps [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API)? I do not have any experience with that though.

**Comment by sahil48** [comment]
I was the one who had originally suggested the feature. One of the things I liked about the edge sidebar is that it gave equal space to each session. One row for every session. In Tabs aside, you can see every website, which is good, but you may have to scroll through a ton on websites before seeing the next session. In contrast it would be good (in the collapsed view) to have a single row preview with a few of the websites (horizontally layed out, with left and right buttons to see the next few websites possibly) in the session to make it easy to get a flavor of what websites are in the session. To get a full list, you expand the session as you normally do.

**Comment by jens-t** [comment]
I would like to help with the ux design of the tabs aside extension. This seems to be a good starting point.

I will take a closer look at the edge implementation, incorperate the ideas from this thread and provide a PR, if thats ok?

Considering the thumbnail idea: i dont think there is enough space in the sidebar for a sensible design with site thumbnails, maybe instead going for the site favicons would be better? favicons work better in small sizes, at least in a collapsable list view, which seems to be a good fit for this kind of data ...

As a later addition one could still add another layout, like a thumbnail grid with 2-5 columns and minimal text label ...

**Comment by tim-we** [comment]
Thanks, any help is greatly appreciated. As you may know I am currently working on Tabs Aside v3 which is rewritten from scratch (including the sidebar). Different layouts is already supported (the option for this is currently hidden from the user).
These Layouts extend the class TabView and are placed in this folder: https://github.com/tim-we/tabs-aside/tree/typescript/ts/sidebar/TabViews. I am planning to ship v3 with the current SimpleList and an a favicon view, though I am not completely sure how that is supposed to look. 

The current development branch is `typescript`. With the release of v3  this will be merged to the `master`.
You can check out a preview of v3 without cloning & compiling the code yourself [here](https://github.com/tim-we/tabs-aside/releases/tag/v3-alpha.3).
If you want to build it yourself check out the [dev guide](https://github.com/tim-we/tabs-aside/wiki/Development).
Since v3 is not finalized yet and the code is still gonna change it would be better to create some drafts for discussion first

**Comment by jens-t** [comment]
> Thanks, any help is greatly appreciated. As you may know I am currently working on Tabs Aside v3 which is rewritten from scratch (including the sidebar).

Ah, no i didn't :) i will have a closer look.

> Since v3 is not finalized yet and the code is still gonna change it would be better to create some drafts for discussion first

what do you mean with drafts? sample PR's based on the typescript branch or html screenshots or somethng else? (i would go with PR's and discuss these directly)

> I am planning to ship v3 with the current SimpleList and an a favicon view, though I am not completely sure how that is supposed to look.

i could help you with this, i have some experience with ui design, not so much with typescript, but that shouldn't be a hurdle as i'm not new to js :) ... i think the css also needs some refactoring. let me take a closer look and get back at you with some new tickets where i would address things i would change, one by one. in general i would be interested to refactor the whole ui towards a more consistend and usable one. maybe we start with some little things to find a workflow and go on with the bigger things from there ...

> You can check out a preview of v3 without cloning & compiling the code yourself here.
> If you want to build it yourself check out the dev guide.

thanks for the links!

**Comment by tim-we** [comment]
> what do you mean with drafts? sample PR's based on the typescript branch or html screenshots or somethng else? (i would go with PR's and discuss these directly)

I was thinking screenshots but if you want to go with PRs thats cool too.

> i could help you with this, i have some experience with ui design, not so much with typescript, but that shouldn't be a hurdle as i'm not new to js :) ... i think the css also needs some refactoring. let me take a closer look and get back at you with some new tickets where i would address things i would change, one by one. in general i would be interested to refactor the whole ui towards a more consistend and usable one. maybe we start with some little things to find a workflow and go on with the bigger things from there ...

I already started refactoring the css a little bit. I am not sure whats the best way to do this so I am open to any suggestions. Currently TabViews have their own styles defined in a separate css file placed in https://github.com/tim-we/tabs-aside/tree/typescript/dist/css/sidebar/tab-views.

**Comment by tim-we** [comment]
Also the [`TabData` class](https://github.com/tim-we/tabs-aside/tree/typescript/dist/css/sidebar/tab-views) has a `getFavIconURL()` method, I suppose that will be handy ;)
Of course a proper implementation should cache the favicons locally but I am not sure yet whats the best way to do this. I think that is something that can be improved later on.

**Comment by jens-t** [comment]
As you're already using webpack, i would go with sass instead of vanilla css. and migrate to a design system based approach. that would include a naming convention, like rscss or something similar. and an atomic design like folderstructure, for example modules, components and so on ...

In sass i would extend the variable use, include colors and other things. And clean up the css structure.

I would make a PR for all of this, if that works for you ...

**Comment by jens-t** [comment]
> Also the TabData class has a getFavIconURL() method, I suppose that will be handy ;)
Of course a proper implementation should cache the favicons locally but I am not sure yet whats the best way to do this. I think that is something that can be improved later on.

I'm not sure, but if servers workers are available in web extensions this would be the best way to handle caching ...

**Comment by tim-we** [comment]
> As you're already using webpack, i would go with sass instead of vanilla css. and migrate to a design system based approach. that would include a naming convention, like rscss or something similar. and an atomic design like folderstructure, for example modules, components and so on ...
> 
> In sass i would extend the variable use, include colors and other things. And clean up the css structure.

I have no experience with SASS but that sounds reasonable.

> I would make a PR for all of this, if that works for you ...

That works for me :)

**Comment by jens-t** [comment]
> I have no experience with SASS but that sounds reasonable.

It's easy to get into Sass, you can always ask me if you have questions or need an introduction.

> That works for me :)

Ok, i'll send a PR, we can then look together at the new css/sass structure ...

I now had a closer look at the "typescipt" codebase. And one thing that bugs me, is that the html is so tightly coupled with the js, maybe we can improve on this later. I have some suggestions on how to improve especially the views. let's see if there is something that works also for you. i'll make a proposal in a second PR.

When that's done, i could focus on the ui design (css/html) and you could focus on the functional part (js). Dividing the HTML from the js makes also development easier, as long as we're not going for a complete rewrite with a component based approach (vue/react), but i think that would be way too much tooling for this little extension :) Let's keep it simple, just a bit cleaner ...

I'm sorry if these proposals are a bit harsh, as the "typescript" codebase is basically a brand new rewrite, so i could understand, if you want to leave the js/html coupling as it is at the moment. Let's see where we get, but make sure you stay comfortable with the codebase, if anything i suggest seems to much or not in your interest, then please feel free to say no, i will understand :)

**Comment by tim-we** [comment]
You have to select a bookmark folder in the addon options. After that the sidebar will work. Previous versions automatically search for it or create it but this is not implemented yet.
Thanks for letting me know about that build problem, I did work for me.

> And one thing that bugs me, is that the html is so tightly coupled with the js

Could you elaborate on this? Perhaps we should move this conversation to E-Mail?
Generally speaking I am open to improvements in this regard.

**Comment by Weasy666** [comment]
Regarding the layout/UI/UX you could maybe take a look at this Firefox extension [Set Aside](https://code.guido-berhoerster.org/addons/firefox-addons/set-aside/). Dunno, maybe you could even work together.
