### ISSUE TITLE
Ignore Pinned Tabs feature does not work.

### ISSUE THREAD

**Issue by KaiPrince** [tim-we/tabs-aside#43]
When the feature is enabled, the Set Tabs Aside behaviour is the exact same i.e. all tabs, including the pinned tabs, are set aside.

**Comment by tim-we** [comment]
Good catch. I am currently quite busy but I will continue working on the extension in October. The next major version is currently in development (the `typescript` branch) and I will make sure this will work in v3 which is currently scheduled to ship with Firefox 63 (https://github.com/tim-we/tabs-aside/milestone/4). 

If that's too long for you let me know and I will fix it in early October (or perhaps someone else gives it a try). Sorry if this caused any inconvenience.

**Comment by privatesam** [comment]
Love this extension but the pinned tab bug is a killer.  Thanks for the development of this though!

**Comment by tim-we** [comment]
Turns out this was a simple fix. Sorry that it took so long. I submitted a new version to the addon store.
