### ISSUE TITLE
Feature Request: Integration with Synced Tabs

### ISSUE THREAD

**Issue by sahil48** [tim-we/tabs-aside#46]
Similar to the integration with pocket idea, integration with Synced tabs from my phone or tablet would be great. I like to set aside tabs I have opened on my phone or tablet (via firefox for iPhone or iPad), and opening 100 tabs and setting them aside is currently a very memory intensive process. An easier way to do this would be much appreciated.

**Comment by tim-we** [comment]
AFAIK there is no way for extension to access synced tabs, so I am not sure what can be done about that. Any ideas?

**Comment by sahil48** [comment]
I don't have any ideas for accessing the synced tabs via an API.

I'll try to describe the objective. When I open a ton of tabs, I'm looking for tabs aside to intercept them before they get loaded in Firefox's memory and get bookmarked immediately. Synced tabs, and other tools like multi-links let you open all your tabs at one time, but they take up a ton of memory, and cause firefox to freeze and crash. When you bookmark all tabs, there is no good way to determine if you are bookmarking the right URL or an about:blank page (tab's aside leaves these about:blank pages open so that you have the option and ability to reload and try setting the tab aside again).

As an alternative, it would be great if you can have a set-aside mode you can toggle on and off, so that any tabs you open using open-all-tabs command, or tools like multilinks, get set aside immediately as they are getting opened and loaded. This type of behavior is more general than the one I identified in this Feature Request, and would have more use cases.
