### ISSUE TITLE
Popup Menu order

### ISSUE THREAD

**Issue by rayman89** [tim-we/tabs-aside#51]
Could you allow to re arrange the order of the popup menu? Many times it happened to me that I wanted to see the sessions I had and selected "tabs aside" by mistake. If that's not possible a confirmation dialog would be niece (or even both if you think it could be better). Thank you.

**Comment by tim-we** [comment]
Good idea. I will rearrange them for the upcoming version (3). Not to sure about the confirmation dialog though.
