### ISSUE TITLE
Feature request: Custom session name template

### ISSUE THREAD

**Issue by Gubith** [tim-we/tabs-aside#58]
Feature request: Folder name option for yyyymmdd-hhmm
That's enough for me.  This makes folders sortable and time to distinguish more than one.

Further complexity [yyyymmdd] [hhmm] [manual text] [first tab title]

I like that it doesn't ask for a name every time!  thanks.

A few more steps and this addon will challenge the best chrome version.

**Comment by tim-we** [comment]
Good idea, I will make that template a user customizable option. 
Not really sure what you mean by [manual text] since sessions can be renamed anyway...?
