### ISSUE TITLE
Tabs Aside! toolbar button has disappeared

### ISSUE THREAD

**Issue by jmtd** [tim-we/tabs-aside#59]
A weird one this one. My "Tabs Aside!" button has disappeared.  The extension is enabled, v2.6; I've tried toggling between light/dark background (default was black) to no avail. It was in my "more tools…" overflow, and is no longer there nor in the list of options to choose from when I select "Customise Toolbar". Firefox 66.0.5 (64-bit), on Linux, I tried restarting the browser to no avail.

**Comment by jmtd** [comment]
Hold the front page! It had just transformed into the "active sessions" icon. I'd not seen this before; personally I find it a bit confusing for the top-level button to change its behaviour like that. But that's not the bug I was reporting, so I'll close this.

**Comment by tim-we** [comment]
That sounds very weird. Not sure though what you mean by "active sessions" icon? 
For a dark theme it should look like this:
![image](https://user-images.githubusercontent.com/10491533/57800896-c9e89f80-7752-11e9-9739-05507f801e2c.png)

The icon can only be changed by the code for the "Browser action icon" setting in the options page.
If it does not look like in the above image (except the color) it is a bug, though probably a bug with Firefox not the extension.
