### ISSUE TITLE
sidebar session management

### ISSUE THREAD

**Issue by tim-we** [tim-we/tabs-aside#6]
feature requests regarding this include:
- reordering sessions
- delete single tabs from a session

**Comment by JordyScript** [comment]
Another nice feature would be integration with Multi-Account containers.

- Setting aside tabs should preserve their container information, such that restoring tabs makes them open in the same container they were saved from.
- Another option would be to open an entire container or individual tabs inside of a specified container, overriding any original container information.

**Comment by JordyScript** [comment]
> For [keyboard shortcuts] number 3 and 4 to be most useful, a user should have the ability to reorder saved sessions manually, as well as determine whether new saved sessions are added to a queue or a stack (i.e. come in last extending the queue, or come in on top, heightening the stack)
- JordyScript in Issue #7 

Thought this deserved  mention here as well, cuz this is where the two Issues overlap.
