### ISSUE TITLE
Named windows workflow - project work concept

### ISSUE THREAD

**Issue by ootada** [tim-we/tabs-aside#60]
- I want every project i do work on to be represented by named firefox window that i can set aside, so:
- I want to set aside whole windows at a time, all its tabs and state
- I want setting aside to not touch other open windows at all
- I want the name i give to sessions to show as firefox window title (there is extension for setting window titles, possibly integrate? - "[Crappy firetitle](https://addons.mozilla.org/en-US/firefox/addon/crappy-firetitle/)" )
- It would be nice for named session to add new tabs from same named window automatically, and possibly put closed tabs in that window into some form of undo history. Micromanaging tabs then could be left to the browser (like, moving tabs from one window to another automatically would move them from one session to the another).

In an ideal future I imagine the project work concept would allow saving/restoring groups of windows of different apps on OS level (or, possibly, other apps integrated as browser tabs, or, alternatively, whole virtual desktops) to quickly set aside and restore all the work related to a specific project.

**Comment by tim-we** [comment]
By default the next version (v3) will work like that, "tabs aside" will set aside tabs from the current window, restore will open sessions in their own new window. Firefox allows extensions to set a prefix for window titles, that could be used to display the session title.
Micromanaging tabs like that is already implemented and will ship with v3 (check out https://github.com/tim-we/tabs-aside/releases/tag/v3-alpha if you want to give it a try)

**Comment by tim-we** [comment]
- as of v3 sessions have their own window by default
- the session title will be the title preface of the window
- micromanaging tabs by moving them between windows is also supported
