### ISSUE TITLE
Feature Request: Quick session access with right-click on button

### ISSUE THREAD

**Issue by Pinetrax** [tim-we/tabs-aside#65]
Since I mainly just open a session and then immediately close the sidebar, it would be nice to have some kind of shortcut to open a session more quickly.

I propose doing a right-click and there having the last x sessions available to open would be a neat feature. That way you avoid opening the popup, then opening the sidebar and after that closing it again. An overflow menu after showing the last x sessions would be an option to avoid not having all sessions in the menu.

**Comment by tim-we** [comment]
Implemented! 

![image](https://user-images.githubusercontent.com/10491533/74589951-4bcf6700-500a-11ea-8c64-c0d3beca9239.png)
