### ISSUE TITLE
keyboard shortcuts

### ISSUE THREAD

**Issue by tim-we** [tim-we/tabs-aside#7]

**Comment by JordyScript** [comment]
A few nice shortcuts would be: 

- Keyboard shortcut to set aside all tabs in a window
- Keyboard shortcut to show/hide saved sessions/sidebar
- Keyboard shortcut to open first 9 most recent sessions using numerical keys

**Comment by tim-we** [comment]
Sounds good. Any idea for the actual keys to press? Those need to be set in the manifest.json ([see MDN](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands)) and can not be changed by the user (AFAIK).
If the focus was on the sidebar or some other page controlled by the extension user-specified shortcuts could work.

**Comment by JordyScript** [comment]
1. Keyboard shortcut to set aside all tabs in a window
-  (`Ctrl`) + `Alt` + `a`  | mnemonic: alternatively control setting _A_side
// control doesn't have to be there as ALT A is free, but you are controlling the tabs, so it is mnemonically nice to have it, and it keeps ALT A free for something else. Of course Alt A saves you a keystroke. What are your thoughts?
2. Keyboard shortcut to show/hide saved sessions/sidebar
-  (`Ctrl`) + `Alt` + `s`  | mnemonic: alternatively control _S_idebar
// control doesn't have to be there as ALT S is free, but you are controlling the tabs, so it is mnemonically nice to have it, and it keeps ALT S free for something else. Of course Alt S saves you a keystroke. What are your thoughts?
3. Keyboard shortcut to open first 9 most recent sessions using numerical keys
-  `Alt` + `Shift` + `1` through `9` | Alternatively shift the session numbered _X_ from the sidebar to the tabbar (i.e. opening them)
// For number 3 and 4 to be most useful, a user should have the ability to reorder saved sessions manually, as well as determine whether new saved sessions are added to a queue or a stack (i.e. come in last extending the queue, or come in on top, heightening the stack)
4. Set aside the active tab to an already existing saved session (1-9)
-  `Ctrl` + `Alt` + `Shift` + `1` through `9`  | Control the Active tab: Alternatively shift the _A_ctive tab to the session numbered _X_ (i.e. set it aside to session X)

**Comment by tim-we** [comment]
1. and 2. sound good, I would prefer the `Ctrl` version. 

I am not sure about 3. and 4. I think a shortcut that opens a small session selector popup that allows you to search for a session by name (and perhaps content) and select by `Enter` might be better because the session order would not matter. That might be more accessible for people that do not use the extension on a daily basis. What are your thoughts about that?

**Comment by tim-we** [comment]
Firefox does not allow `Ctrl`+`Alt`+... shortcuts. `Alt`+`A` works fine but `Alt`+`S` (this will open the history menu). I have set up a [jsfiddle](https://jsfiddle.net/gtphsc0v/1/) to check if a shortcut is valid (using the regular expressions Firefox uses for that validation).

**Comment by JordyScript** [comment]
Your idea for a session selector pop-up short cut does sound more accessible, and it is also more general, as it provides access to all set aside groups not just the first 9. However this is at the cost of efficiency, as more keystrokes are needed. All in all one could make a justifiable case for such a shortcut as you propose.

In defense of the 3rd and 4th idea I shared. Session order would no longer be a problem if the sidepanel showing the sessions and their titles and indices are shown, as they serve as a visual reminder of the shortcut keys necessary to access them.

**Comment by JordyScript** [comment]
Thanks for that jsfiddle. I didn't know Firefox does not allow  `Ctrl`+`Alt`+... shortcuts. I used [this page](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly) to determine if key combinations were available, but was not aware of these limitations.

With regards to the `Ctrl`+`Shift` + ... shortcuts: I expected as much... they run out rather quickly.
`Alt `+ `Shift `+ `L `and  `Alt `+ `L `are still free for session selector shortcuts for moving the focused tab to an exiting list, and opening an existing list respectively. What do you think about those?

**Comment by tim-we** [comment]
`Ctrl`+ `Alt` + ... shortcuts are for some reason not allowed as global shortcuts. They would still work in a website context like the sidebar (if the focus was on the sidebar). 
`Alt`+`Shift`+`L` and `Alt`+`L` seem good idea.
Still need a shortcut for the sidebar though.

**Comment by JordyScript** [comment]
So to open the side bar we could simply use `Alt` + `Q` and then maybe `Alt` + `Shift` + `Q` for setting all tabs aside. That way we only use 2 different letters `Q `and `L `where we group similar functionality together, which might be easier to remember than a different letter for each functionality. `Q `then manipulates all tabs/ all sessions, whereas `L `manipulates the focused tab and/or a specific session.

This time there's no reason for choosing `Q `other than that `Q `seems to be a seldomly used key for shortcuts, which also limits potential conflicts with third party add-ons, (`Q `is unused afaik except for `Ctrl `+ `Shift `+ `Q` which closes the firefox session).

**Comment by tim-we** [comment]
Good idea. All of those are fairly easy to press with one hand and I also like the grouping of similar functionality. `Alt`+`Q` and `Alt`+`Shift`+`Q` will be part of the next update, which will still take some time unfortunately. `Alt`+`L` and `Alt`+`Shift`+`L` will follow when session reordering is implemented (hopefully shortly after). Thanks for your input.
