### ISSUE TITLE
inconsistent behaviour of "Save tabs as session"

### ISSUE THREAD

**Issue by ootada** [tim-we/tabs-aside#71]
- open new ff window
- open a few tabs
- click on 'tabs aside' icon
- select "save tabs as session" (says "Turn the tabs from this window into a session" on the hover)
= new session appears with tabs from the window
- open a few more tabs
= !! newly opened tabs do not become part of the session
- rename the session
- close window
= !! session disappears from the session list, no tabs saved

**Comment by tim-we** [comment]
Thanks for the report, I was able to reproduce this. I will have a look into it and hopefully fix it later today.

**Comment by tim-we** [comment]
Tabs Aside 3.3 which contains a fix for this has just been released on AMO.
