### ISSUE TITLE
Error: Title may only be set for discarded tabs

### ISSUE THREAD

**Issue by feofan-msk** [tim-we/tabs-aside#78]
Throws an error after turning off lazy loading
![изображение](https://user-images.githubusercontent.com/30575877/78021023-e3470a00-736b-11ea-9c00-01c90b6d0b04.png)

Works fine with lazy loading on

**Comment by tim-we** [comment]
Not sure how that one slipped through but I will fix it ASAP. Thanks!

**Comment by tim-we** [comment]
The bug is fixed now and the new version has already been approved by Mozilla so check for updates! Thanks again for submitting this.

**Comment by jmtd** [comment]
I just got this now with Firefox 88.0.1 and Tabs Aside 3.6.0. I have Lazy loading off. I don't know if it was on when I saved the session. I've now lost the session (due to #112) so I can't report on what the saved data is (or was) for the session.
