### ISSUE TITLE
Request: support ISO 8601 date format in the title template (double digit month and day)

### ISSUE THREAD

**Issue by egabrum** [tim-we/tabs-aside#95]
Currently, $M and $d default to single-digit numbers, which does not allow sorting sessions by date.
Of course, they are sorted by date to start with, but they might be reshuffled and, in general, it's good practice to support ISO 8601.

Options:
1. Make $M and $d default to double-digit numbers.
2. Offer new variables that use double-digits.
3. Offer new variable that returns the date in YYYY-MM-DD format

**Comment by tim-we** [comment]
I chose single-digit numbers as sidebar space is rather limited. But I do not mind additional variables.

**Comment by tim-we** [comment]
I added `$dd` and `$MM` (see https://github.com/tim-we/tabs-aside/wiki/Session-title-template-variables). This is included in version 3.5.0 which is available on AMO.
