### ISSUE TITLE
Some color layout to distinguish between "restore" >< "set aside"

### ISSUE THREAD

**Issue by m2habert** [tim-we/tabs-aside#96]
I don't want to be the nitpicker... But as I rely more and more on tabs-aside, the number of sessions has been growing as well as the "open" and "closing" of same. Therefore, visual confusion has also becoming more present. 

So a colour bullet would be much useful. I've no idea what the usual pattern is (¿red dot for "restore"=closed vs green for "set aside" = currently active?), but anything would help.

Actually, there is really no need for a pair: coloured dots eclusively for the active sessions would be enough.

Thanks

**Comment by tim-we** [comment]
Yes I agree. Working on it.

**Comment by tim-we** [comment]
I came up with this (https://github.com/tim-we/tabs-aside/commit/1a7103dda03cffbb7f49ee0fe1a08874c793bc0e):
![image](https://user-images.githubusercontent.com/10491533/89225566-b08f7580-d5da-11ea-824e-697cffaebd55.png)

What do you think?

**Comment by m2habert** [comment]
Pretty neat!
