### ISSUE TITLE
Active session not properly updating

### ISSUE THREAD

**Issue by knmoreland** [tim-we/tabs-aside#97]
Hello, Active sessions work well tracking changes to tabs that are already up, but when I add more tabs to the window, I'd like these to be tracked as changes to the session as well. In a brand new saved session, this tracks fine, but when I load an previous session, this does not update.

**Comment by tim-we** [comment]
New tabs added to a sessions window should be added to session and tracked. Just gave it a try and its working for me. Note that this only works if the session has its own window. So make sure you have the setting "Open sessions in a new window" enabled. If its still not working as intended I need some more info (steps to reproduce, version and perhaps even OS)
