### ISSUE TITLE
Sidebar should not be shown on every session

### ISSUE THREAD

**Issue by Gruski** [tim-we/tabs-aside#99]
The fact that the Sidebar is visible every-time I open a new browser is really annoying. It should only show if explicitly opened though either the toolbar menu or the shortcut. I don't use this feature all the time and don't want it to be constantly in my face taking browser real-estate. If other users like it like this, at least make it an option to not open every time.

**Comment by tim-we** [comment]
That might be a Firefox bug, my Firefox does not do that. Actually, extensions cannot control that behavior.

I disabled the sidebar showing up after install (https://github.com/tim-we/tabs-aside/blob/c0042968765ead9fea2234a4ac9ff451a27a45c7/src/manifest.json#L53) but there are no other [properties](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/sidebar_action) one can change.
Extension can close the sidebar but only in response to a user action like a click on an extension button or shortcut press.

So unfortunately there is nothing I can do here, sorry. You can close the sidebar by pressing `Alt + Q`, that might be a bit faster. Unless you think I'm missing something please close this issue.

**Comment by Gruski** [comment]
I don't know enough about developing extensions to know if you're missing something but for me it always shows and have to close it every time. Firefox v79. Guess I'll be moving on to another extension.
